### ISSUE TITLE
Use handlebars with default main layout

### ISSUE THREAD

**Issue by Aragur** [fastify/point-of-view#112]
I recently migrated my app from express to fastlify. It's awesome what it did performance wise :+1:  
 
I'm using Handlebars as my view engine, using a `layouts/main.hbs` which has all the boilerplate code. (Head, Loading Spinner, etc.)  
But how can I configure point-of-view to use the main layout by default?  
I tried it using all options with no success...

**Comment by mcollina** [comment]
Can you make an example we can work with? Maybe point-of-view is missing some features!

**Comment by AragurDEV** [comment]
Done, here is a small example: https://github.com/AragurDEV/fastify-point-of-view-example

**Comment by mcollina** [comment]
Unfortunately I don't know how to help, as I'm not super familiar with handlebars. A PR would be welcome.

**Comment by nikea1** [comment]
I've been trying to figure out this problem too. I think it has to deal will how the view engine is set up right now. I compared the engine express-handlebars uses and the one point of view uses. In summary, the express-handlebars render twice. One for the main then one for the layout to put in the main body. Meanwhile, point-of-view is set to only render one template it seems. So if you want something like express-handlebars your best bet right now is writing a plugin that handles that double compile-rendering process. Unfortunately, I have no idea where to begin. I don't know enough handlebars to even begin to make such a plugin.

**Comment by francisbrito** [comment]
Since layouts are a `handlebar-express`-package-specific feature, I think this could only be achieved by doing the two-step-render process @nikea1 described at the handler-level, e.g:

```js
fastify.get('/', async (request, reply) => {
  const html = await fastify
    .view('home.hbs', {})
    .then(body => fastify.view('layout.hbs', { body, title: 'It works!' }))

  reply.type('text/html').send(html)
})
```

given a `templates/layout.hbs` like this:
```handlebars
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{title}}</title>
</head>
<body>
<section class="main">
{{{body}}}
</section>
</body>
</html>
```

and a `templates/home.hbs` like this:
```handlebars
<h1>This is home</h1>
```
--
I could open a PR to "bake" this functionality into `point-of-view` plugin, if it makes sense @mcollina

**Comment by mcollina** [comment]
I think that make sense, send a PR over. However we need to make sure that either:

1. we throw nicely for other engines
2. we implement some similar feature for them

**Comment by mohd-akram** [comment]
Handlebars supports layouts via [partial blocks](https://handlebarsjs.com/guide/partials.html#partial-blocks) and [inline partials](https://handlebarsjs.com/guide/partials.html#inline-partials).

**Comment by Eomm** [comment]
> Handlebars supports layouts via [partial blocks](https://handlebarsjs.com/guide/partials.html#partial-blocks) and [inline partials](https://handlebarsjs.com/guide/partials.html#inline-partials).

Could you elaborate?
I don't understand the point

**Comment by mohd-akram** [comment]
You can do layouts like this:

`home.hbs`:

```handlebars
{{#> layout title="Home page"}}

{{#*inline "body"}}
Hello world
{{/inline}}

{{/layout}}
```

`layout.hbs`:

```handlebars
<!doctype html>
<html lang="en">
  <head><title>{{title}}</title></head>
  <body>{{#> body}}{{/body}}</body>
</html>
```

`app.js`:

```javascript
module.exports = async function (fastify, opts) {
  fastify.register(require('point-of-view'), {
    engine: { handlebars: require('handlebars') },
    options: { partials: { layout: 'layout.hbs' } }
  });
  fastify.get('/', async (request, reply) => {
    reply.view('home.hbs');
  });
};
```

**Comment by chinhtrandn** [comment]
Can i set Partials folder?

**Comment by Uzlopak** [comment]
@chinhtrandn 
according to tests, yes
https://github.com/fastify/point-of-view/blob/f218d2eaaec32a76ddbf43bac4edb6b79c6011d1/test/test-handlebars.js#L604

**Comment by Eomm** [comment]
#136 and #141 implemented this issue

closing
