### ISSUE TITLE
art-template support

### ISSUE THREAD

**Issue by huaentandd01** [fastify/point-of-view#116]

**Comment by StarpTech** [comment]
Hi @huaentandd01 please create a proper issue otherwise nobody will care about it. Link to the framework, Would you like to send a PR? etc.. thanks.

**Comment by huaentandd01** [comment]
sorry, an excellent template engine [art-template](https://aui.github.io/art-template/docs/index.html) supported will be better

**Comment by mcollina** [comment]
A PR to add that would be welcomed.

**Comment by farzer** [comment]
i use my personal account to pr 😢

**Comment by Eomm** [comment]
Released in 3.3.0
