### ISSUE TITLE
useHtmlMinifyStream appears broken

### ISSUE THREAD

**Issue by tigt** [fastify/point-of-view#124]
I’ve made a reduced test case at [tigt/streaming-html-minifier-reduced-test-case](https://github.com/tigt/streaming-html-minifier-reduced-test-case).

If you comment out `useHtmlMinifier` and comment in `useHtmlMinifyStream`, the rendered HTML is not minified. However, for the reverse, it is. Am I doing something wrong?

**Comment by mcollina** [comment]
I don’t understand the issue. Would you mind providing a bit more instructions on how to reproduce?

If you think this is a bug and you’d like to send a PR, that’d be great!

**Comment by tigt** [comment]
I would be happy to make a PR, but I don’t quite understand what’s happening yet.

In the test case, I have a marko template:

```marko
<!doctype html>
<html lang="en">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">

The following element should be minified:
<p id="" class="">
&nbsp;
</p>
</html>
```

If I set up the `useHtmlMinifier` option like so:

```js
fastify.register(require('point-of-view'), {
    engine: { marko: require('marko') },
    templates: 'components',
    includeViewExtension: true,
    options: {
      useHtmlMinifier: require('html-minifier'),
      htmlMinifierOptions: {
        collapseWhitespace: true,
        conservativeCollapse: true,
        collapseBooleanAttributes: true,
        removeEmptyAttributes: true,
        decodeEntities: true,
        includeAutoGeneratedTags: false,
        removeOptionalTags: true,
        removeAttributeQuotes: true,
        removeEmptyAttributes: true,
        removeScriptTypeAttributes: true,
        removeStyleLinkTypeAttributes: true
      }
    }
  }
)
```

Then my output looks like this:

```html
<!doctype html><html lang=en><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"> The following element should be minified: <p> 
```

So far, so good.

However, when I try to use `useHtmlMinifyStream` like how the README suggests:

```js
fastify.register(require('point-of-view'), {
    engine: { marko: require('marko') },
    templates: 'components',
    includeViewExtension: true,
    options: {
      useHtmlMinifyStream: require('html-minify-stream'),
      htmlMinifierOptions: {
        collapseWhitespace: true,
        conservativeCollapse: true,
        collapseBooleanAttributes: true,
        removeEmptyAttributes: true,
        decodeEntities: true,
        includeAutoGeneratedTags: false,
        removeOptionalTags: true,
        removeAttributeQuotes: true,
        removeEmptyAttributes: true,
        removeScriptTypeAttributes: true,
        removeStyleLinkTypeAttributes: true
      }
    }
  }
)
```

…the output looks like this:

```html
<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"> The following element should be minified: <p id="" class="">&nbsp;</p></html>
```

Which is not minified.

**Comment by Eomm** [comment]
That is the output from `html-minify-stream` so maybe the issue is in that module?

**Comment by tigt** [comment]
After looking into it, I believe so.

However, after inspecting the source of `html-minify-stream`, I’m not sure what benefit it provides over `useHtmlMinifier` in `point-of-view` — it seems to buffer the stream until complete, then minifies it (with `html-minifier`), then flushes.

I was under the impression it would minify the HTML as a stream to leverage Marko’s streaming templates, but looks like I was mistaken. I no longer care about fixing the underlying problem with `html-minify-stream` as I’m not going to use it, but maybe it shouldn’t be mentioned in `point-of-view`’s README if it doesn’t work/doesn’t seem to improve on `useHtmlMinifier` if it _did_ work.
