### ISSUE TITLE
Make the data-parameter of `.view(page, data)` for all template-engines optional.

### ISSUE THREAD

**Issue by florianb** [fastify/point-of-view#132]
Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/fastify) or [Fastify Help](https://github.com/fastify/help) and ask any questions you have or mention any problems you've had getting started with Fastify.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

## 🚀 Feature Proposal

Make the data-parameter of `.view(page, data)` for all template-engines optional.

I already created the corresponding PR #131.

This seems to catch up to the PR #52.

## Motivation

I use the view-function often with implicitly provided data via the `defaultContext`. Currently this efforts in any case (than the pure `ejs`-template-handler) that an empty objeckt (`{}`) must be provided.

Since the pure [`ejs`-view-function](https://github.com/fastify/point-of-view/blob/master/index.js#L171) treats the data-parameter already as optional, i expected it to be optional for the other template-engines, too.

### Current syntax

```js
  fastify.register(require('../index'), {
    engine: {
      'ejs-mate': require('ejs-mate')
    },
    defaultContext: { text: 'text' },
    templates: 'templates'
  })

  fastify.get('/', (req, reply) => {
    reply.view('index.ejs', {})
  })
```

### Future syntax

```js
  fastify.register(require('../index'), {
    engine: {
      'ejs-mate': require('ejs-mate')
    },
    defaultContext: { text: 'text' },
    templates: 'templates'
  })

  fastify.get('/', (req, reply) => {
    reply.view('index.ejs')
  })
```

**Comment by Eomm** [comment]
#131 landed 👍
