### ISSUE TITLE
`layout` should be in `options`

### ISSUE THREAD

**Issue by arniu** [fastify/point-of-view#141]
`layout` is optional for some template engines.
So it's supposed to be under `options` as others.

**Comment by arniu** [comment]
Related to #112

**Comment by alex2844** [comment]
```
koaEjs(app, {
    root: path.join(__dirname, 'view'),
    layout: 'template',
    viewExt: 'html'
});
```

[google tranglate]
Thus, I connected templates in koa, in fastify instead of root - templates, but I did not find layout and viewExt

[orig_ru]
Таким образом подключал шаблоны в koa, в fastify вместо root - templates, а вот layout и viewExt не нашел

**Comment by alex2844** [comment]
https://github.com/fastify/point-of-view/pull/146
