### ISSUE TITLE
Missing property defaultContext in PointOfViewOptions in TS declaration file

### ISSUE THREAD

**Issue by ni1son** [fastify/point-of-view#142]
## 🐛 Bug Report

`defaultContext` property is missing in `PointOfViewOptions` interface in TypeScript declaration file [index.d.ts](https://github.com/fastify/point-of-view/blob/master/index.d.ts) although the property is described in the README

**Comment by mcollina** [comment]
would you like to send a PR?
Il 15 gen 2020, 12:04 +0100, Ilya Staheev <notifications@github.com>, ha scritto:
