### ISSUE TITLE
Promise not fulfilled when using res.view

### ISSUE THREAD

**Issue by samevision** [fastify/point-of-view#144]
Hello,

I just want to render a page with variables. Passing getting the variables and passing them with res.send works fine but if I use res.view I get an error that the promise is not fulfilled. I am pretty new to Javascript and especially to async functions.

My code looks as follow:
```
exports.show = async (req, res) => {
	try {
		const [var1, var2] = await Promise.all([
			getUser(id),
			getInfo(id)
		])
		res.view("index.pug", {var1: var1, var2: var2})
	} catch {
		if (err) throw err
	}
}
```

What am I doing wrong?
Thanks

**Comment by mcollina** [comment]
just do 

return res.view("index.pug", {var1: var1, var2: var2})

**Comment by samevision** [comment]
I already tried that. Same error message unfortunately.

**Comment by samevision** [comment]
Fastify: 2.11.0
Point-of-view: 3.7.0

**Comment by mcollina** [comment]
Try https://github.com/fastify/point-of-view/blob/434910ccac32c4d8157815912da45d4731431e4d/example-async.js#L26

**Comment by samevision** [comment]
Solved it! Thank you very much
