### ISSUE TITLE
100% code coverage

### ISSUE THREAD

**Issue by mcollina** [fastify/point-of-view#156]
As titled, this module would benefit from having 100% code coverage

**Comment by gkampitakis** [comment]
Hey Hello, trying to work on this and create a pr for extending code coverage. I have found some places that are easy to be tested an some others are not 100% clear to me. One example I am currently trying to cover is the "caching" part, from some places I can only be sure that is tested if I check coverage report and doesn't seem correct to me. Also I noticed that errors like 
```javascript
catch (error) {
    that.send(error)
    return
}
```
are untested. Can I create a [WIP] pr and give it a shot with some guidance?

**Comment by Eomm** [comment]
Yes! Feel free to open a draft pr
