### ISSUE TITLE
How to access fastify/decorators/global methods/vars?

### ISSUE THREAD

**Issue by dyanakiev** [fastify/point-of-view#164]
How can i access fastify. object or reply decorators here?
Im trying to create a new method for example url() then use it inside the views.

**Comment by dyanakiev** [comment]
Currently i solved this with
```
 fastify.addHook('preHandler', async function (req, reply) {
        reply.url = function (e) {
            return fastify.URL+e;
        };

        reply.static_url = function (e) {
          return fastify.config.STATIC_URL+e;
        };

        reply.uploads_url = function (e) {
          return fastify.config.UPLOADS_URL+e;
        };
    })
```

And passing the reply objec to the view.
```
reply.view('/services/web/template/home', reply)
```


But i dont think thats a good way, are there alternatives without passing the reply object?

**Comment by mcollina** [comment]
A PR that make the `reply` object available inside the views would be highly welcomed.

**Comment by dyanakiev** [comment]
@mcollina this guy https://github.com/fastify/point-of-view/pull/138 back in 2019, did something similar for reply.locals.

 I wonder if i should do something similar and merge the objects, so reply + data passed to the view method.
So the reply data will be available without writing {{reply.test}} and just {{test}} then this could be overwritten when the same key is used when executing reply.view('template', {test: 2}) like that.

**Comment by Eomm** [comment]
You could use [replyDecorators](https://github.com/fastify/fastify/blob/master/docs/Decorators.md) as first steps to avoid the hook

I'm not sure how to provide the `reply` at the view context since it could conflict with other dev parameters o custom view features

**Comment by dyanakiev** [comment]
@Eomm i just found that i can pass defaultContext when initializing and that will be available in each views..

```
fastify.register(require('point-of-view'), {
  engine: {
    ejs: require('ejs')
  },
  defaultContext: {
    reply: fastify.reply
  }
})
```
What if do just that, i will test later, not sure if the fastify,reply is avaiable..

**Comment by Eomm** [comment]
> not sure if the fastify,reply is available its probably not..

Yeah, it exists only when a request is coming

Looking at the code above, you could just move the functions assigned to reply to the default context

```
  defaultContext: {
    confg: fastify.config
  }
```

**Comment by dyanakiev** [comment]
That was fine for functions, but i still need to set some functions or vars globally during a request to the reply object and then access it in templates. For example: loggedIn, im thinking maybe midleware will do fine, but yet accessing from views is a trouble.
