### ISSUE TITLE
Add support for the Eta template engine

### ISSUE THREAD

**Issue by nebrelbug** [fastify/point-of-view#178]
## 🚀 Feature Proposal

Support for the [Eta](https://eta.js.org) template engine. 

## Motivation

Eta is an embedded template engine similar to EJS, but with better performance and more configurability. I'm the creator of Eta, and would love to add support to this project so Fastify users could use Eta.

## Example

_Please provide an example for how this feature would be used._

People would use `point-of-view` with the Eta template engine

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by nebrelbug** [comment]
@mcollina I'd love to! I'll probably submit a PR sometime later this week.

**Comment by nebrelbug** [comment]
Hi @mcollina, just submitted a draft PR at #168. I have all tests passing, but I still need to add documentation.

Let me know what you think!
