### ISSUE TITLE
The idea of many-point-of-view to support multiple template engine

### ISSUE THREAD

**Issue by lanyusan** [fastify/point-of-view#192]
## 🚀 Feature Proposal

Support multiple template engine at the same time.

I'd like to check with point-of-view team if it is something that is aligned with your idea of point-of-view. If you think it is something that can be merged to point-of-view, I would submit a PR, otherwise I will create a package named `many-point-of-view`, obviously I would specify it is derived from point-of-view for our own use.

## Motivation

I am developing a server side application framework with fastify and point-of-view that needs to support multiple sub-sites at the same time with different template engine.

The current design of point-of-view is that that for any registered view instance, the template engine was predefined by the line
`  const engine = opts.engine[type];`  when the view was registerred.

When the `reply.view` is called, this engine is used. There is no way to choose a different engine.

## Example

Some simple hacking of decorateReply could extend point-of-view to support multiple engines, at some minor performance cost ,which wouldn't be a problem except for super busy site. 

The idea is to optionally pass engine name in the format `<engineName>` to `reply.view` as first argument. And decorated view should check if the first parameter starts with '<' to decide if treat it as engine name or as view template path.
And it is safe as '<' isn't a legal path name character. This would also have backward compatibility.

```
  fastify.decorateReply("view", function () {
    if (arguments[0].startsWith("<")) {
      // check if first is engine name
      const args = Array.from(arguments);
      const _engineName = args.shift();
      const engineName = _engineName.substring(1).slice(0, -1);
      const renderer = renders[engineName];
      if (!renderer) throw Error("Not supported engine");
      renderer.apply(this, args);
    } else renderer.apply(this, arguments);
    return this;
  });

```

The engine's view renderrer should add one line: `  const engine = opts.engine["eta"];` which would overshadow the default engine.

I have tested it with eta and marko and it works.

**Comment by Eomm** [comment]
> multiple sub-sites at the same time with different template engine.

But why don't you use the encapsulation?

I don't think you have one route that reply with a different engine (what would it be the benefit?)

```
fastify.register(instance, opts, next) => { 
 // register marko
}, {prefix: '/foo' } )
fastify.register(instance, opts, next) => { 
 // register eta
}, {prefix: '/bar' })
fastify.register(instance, opts, next) => { 
 // register ...
}, {prefix: '/asd' })
```

**Comment by lanyusan** [comment]
I don't use prefix for sub site. 

My application server will be sitting behind a proxy server and use a custom header to specify sub site, and the custom server built with fastify then will resolve to different sub site. The server  has some custom routing rules that isn't particularly standard also. So I would rather prefer this kind of flexibility.

**Comment by Eomm** [comment]
It is now clear to me how you would write a handler.
Let's assume you have all the engine as reply decorator, how would it be the handler for the root path `/`?

Right now I'm 👎 for this feature because for what I understood I image this usage:

```
function handler (request, reply) {
  if(request.headers.customer==='one'){ reply.engineOne.view('/index') }
  if(request.headers.customer==='two'){ reply.engineTwo.view('/index') }
  // etc..
}
```

and in this case, I would approach the problem in a totally different manner

**Comment by mcollina** [comment]
I would prefer a slightly different implementation of this, similar to how https://github.com/fastify/fastify-postgres#name-option work.

I would remove some other wrapping layer essentially. Anyway, send the PR over.

---

(As a side note, saying "my way or I fork" is not a good way to interact with _this_ community)

**Comment by lanyusan** [comment]
@mcollina You read me wrong. I am checking with the team transparently if it is something acceptable for your guys, as I also think it might be against original design principle of point-of-view, and if not, as I need the feature for my project, I would work out something else. I think it is a pretty common way to propose something.

And I am glad @Eomm and you have given some other ideas of how to do it. I would try some other approaches before I send the PR.

**Comment by lanyusan** [comment]
Hi, sorry for the very late following up.

I have found a better way for this with fastify's rewriteUrl and plugin with a prefix. Basically my fastify server will rewrite each subdomain request to a url with the subdomain as prefix. And each prefix can have a plugin with its own view engine.

So problem solved.
