### ISSUE TITLE
Include issue

### ISSUE THREAD

**Issue by dnohr** [fastify/point-of-view#20]
Hi guys,

Have any of you got troubles with including other EJS components within an EJS file? I'm getting following error "Error: Could not find include include file.".

Example:
<% include header %> within the "index.ejs" file.

It works in Express, so maybe I just can't find the relative path somehow. All my ejs files is located in the same folder, so shouldn't be an issue.

Thanks.

**Comment by delvedor** [comment]
Hi! Thank your for checking out Fastify!
Can you create a complete example with a gist?

**Comment by dnohr** [comment]
Hi Tomas,

For sure, check out here:
https://gist.github.com/dnohr/de935d01dc22d5cf45dee34979dda3a1

All the EJS files are located in the same "views" folder, but resulting in the same error:
"Error: Could not find include include file."

I have tried implement the EJS include function in different ways, but can't find the right relative path. This example works fine in Express, but would for sure like to test Fastify :-)

Thanks.

**Comment by delvedor** [comment]
If you are using `include` ejs needs a `filename` option.
```js
'use strict'

const fastify = require('fastify')()
const resolve = require('path').resolve

fastify.register(require('point-of-view'), {
  engine: {
    ejs: require('ejs')
  },
  options: { // this object will be passed to ejs.compile
    filename: resolve('views')
  },
  templates: 'views'
})

fastify.get('/', (req, reply) => {
  reply.view('/index.ejs', {})
})

fastify.listen(3000, (err) => {
  if (err) throw err
  console.log(`Server up: ${fastify.server.address().port}`)
})
```

**Comment by dnohr** [comment]
Super, didn't spot it. Much better!

Thanks for solving it Tomas 👍🏻

**Comment by delvedor** [comment]
You're welcome! If you have more questions or suggestions please open other issues!

**Comment by smartiniOnGitHub** [comment]
Hi all, I spent a lot of time on the same problem ... thanks a lot for the comments in the gist.
Sorry, could you put that info even in some documentation (project README) or one of the samples ? Could be useful to many people ...
Anyway thanks a lot,
Sandro

**Comment by mcollina** [comment]
Sandro, the best approach would be if you open up a PR with the doc/example you think we are missing!

**Comment by smartiniOnGitHub** [comment]
Hi Matteo, I'll do that. Thanks for now.
