### ISSUE TITLE
Manual Cache Eviction

### ISSUE THREAD

**Issue by savearray2** [fastify/point-of-view#201]
## 🚀 Feature Proposal

I apologize if this is a feature already. I'd like to be able to manually evict the LRU cache when in production mode, such that all templates are forcefully reloaded from disk.

## Motivation

I currently have a microservices architecture that allows for new services to be pushed and hot-swapped live while the application is running. In certain cases, we hot-swap ejs files on the fly. Under express, we can force clear the ejs cache using ```app.engine('ejs', ejs.renderFile)``` and ```ejs.clearCache()```.

## Example

I'm not sure what the best way to implement this would be, but honestly anything would be great. (Maybe build off the existing ```fastify.decorate('view')```?)

**Comment by mcollina** [comment]
I would expose it via `app.view.clearCache()` or something similar.

It would be great to add this feature.

**Comment by savearray2** [comment]
@mcollina 

Thank you very much. I've submitted a pull request based on the ```fastify.view.clearCache()``` concept.

**Comment by savearray2** [comment]
This has been merged! Thanks everyone!
