### ISSUE TITLE
it is require to install ejs module

### ISSUE THREAD

**Issue by Adityapanther** [fastify/point-of-view#217]
## 🐛 Bug Report

I am working with template ejs. after installing point of view plugins module I am having err `` cannot find module ejs``

it is require that install ejs or other js template module after installing point of View module or plugins

## Your Environment

- *node version*: 14, 00, 00
- *fastify version*: >=2.0.0
- *os*: Windows

**Comment by mcollina** [comment]
Yes it is required and it's documented in the readme.

**Comment by Adityapanther** [comment]
thanks @mcollina for great job on issue and for great product
