### ISSUE TITLE
`reply.view` seems doesn't return html

### ISSUE THREAD

**Issue by rmlzy** [fastify/point-of-view#225]
Thanks to the fastify team, You guys are doing a great job.

## 🐛 Bug Report

I want get the html string after `point-of-view` plugin rendered.

## To Reproduce

in `example-async.js`:
```js
fastify.get('/', async (req, reply) => {
  const t = await something()
  const html = await reply.view('/index.njk', { text: t })
  console.log('html is:', html) // <== html is undefined
  return html
})
```

## Your Environment

- *node version*: v14.15.1
- *fastify version*: ^3.14.0
- *os*: Mac
- In the nest app, to be exact

Below is my nestjs code:
```typescript
@Controller()
export class DemoController {
  @Get()
  async home(@Res() reply) {
    const html = await reply.view('index.html');
    // I need cache the html to redis.
    return html;
  }
}
```

I don’t know if it’s a bug or my fault. Hoping to get some help.

My English is not very good, if I do not describe clearly at any time to reply me, I will always pay attention to this issue.
Thank you again.

**Comment by mcollina** [comment]
`reply.view()` does not return HTML. the HTML is directly sent back as a response. I'm not sure which part of the doc pointed you to that.

**Comment by rmlzy** [comment]
@mcollina Thanks for your reply, you are right, I am sorry it's my fault.

**Comment by hadihammurabi** [comment]
i need to pre-process rendered page before send it as response.
how to do this?

**Comment by stephanwilliams979** [comment]
any solution facing same problem as i need template response to be stored in variable in order to send in email 


@mcollina please update on this
