### ISSUE TITLE
EJS layout template fails when includeViewExtension is set to true

### ISSUE THREAD

**Issue by jorgevrgs** [fastify/point-of-view#237]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.14.0

### Plugin version

4.14.0

### Node.js version

14.15.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

10.15.7

### Description

When the option `includeViewExtension: true` is defined, then it's not possible to get a layout with the option `layout: 'layouts/layout'`.

### Steps to Reproduce

Create some files:

- plugins
  - point-of-view.js
- view
  - layouts
    - layout.ejs

Register the plugin:

``` js
// plugins/point-of-view.js
'use strict'

const fp = require('fastify-plugin')
const path = require('path')

const plugin = async (fastify) => {
  fastify
    .register(require('point-of-view'), {
      engine: {
        ejs: require('ejs')
      },
      includeViewExtension: true,
      layout: 'layouts/layout',
      root: path.resolve(__dirname, '../', 'view'),
      defaultContext: {
        dev: process.env.NODE_ENV === 'development'
      }
    })
}

module.exports = fp(plugin)
```

Create a layout:
``` html
<!-- view/layouts/layout.ejs -->
<%- body %>
```

Result:

```
Error: unable to access template "layouts/layout"
    at fastifyView (/Users/jorgevrgs/Documents/code/fastify/suramedica-fastify/node_modules/point-of-view/index.js:45:10)
    at Plugin.exec (/Users/jorgevrgs/Documents/code/fastify/suramedica-fastify/node_modules/avvio/plugin.js:132:19)
    at Boot.loadPlugin (/Users/jorgevrgs/Documents/code/fastify/suramedica-fastify/node_modules/avvio/plugin.js:267:10)
    at release (/Users/jorgevrgs/Documents/code/fastify/suramedica-fastify/node_modules/fastq/queue.js:147:16)
    at Object.resume (/Users/jorgevrgs/Documents/code/fastify/suramedica-fastify/node_modules/fastq/queue.js:80:7)
    at Plugin.finish (/Users/jorgevrgs/Documents/code/fastify/suramedica-fastify/node_modules/avvio/plugin.js:246:10)
    at /Users/jorgevrgs/Documents/code/fastify/suramedica-fastify/node_modules/avvio/plugin.js:268:12
    at done (/Users/jorgevrgs/Documents/code/fastify/suramedica-fastify/node_modules/avvio/plugin.js:115:5)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

To avoid that error it's necessary to use the default behavior of `includeViewExtension: false` and to use the extension in each file like `layout: 'layouts/layout.ejs'` and in the controller `res.view('page/home.ejs')`.

### Expected Behavior

With extension required it's working fine:

```
includeViewExtension: false,
layout: 'layouts/layout.ejs'
```

For routes `res.view('page/home.ejs')`

It should work the same without extension (bug here):

```
includeViewExtension: true,
layout: 'layouts/layout'
```

For routes `res.view('page/home')`

**Comment by mcollina** [comment]
Good spot! 
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by jorgevrgs** [comment]
> Good spot!
> Would you like to send a Pull Request to address this issue? Remember to add unit tests.

I'm diving into Fastify recently, so what do you think of modifying `hasAccessToLayoutFile` to allow any extension as showing below because only 'dot', 'ejs', 'hbs', and 'eta' are allowed:

https://github.com/fastify/point-of-view/blob/master/index.js#L610

```js

function hasAccessToLayoutFile (fileName, ext) {
    try {
      accessSync(join(templatesDir, getPage(fileName, ext)))
      return true
    } catch (e) {
      return false
    }
  }
```

The other option, just improving the documentation to offer a solution like using `includeViewExtension: true` you need to define `viewExt: 'ejs'`, or getting the `viewExt` with a function like `{'eta' => 'eta', 'handlebars' => 'hbs', ..theOtherOpts. }` if it's not defined?

**Comment by jorgevrgs** [comment]
An extra detail: When I defined `viewExt: 'ejs'` no matter the value of `includeViewExtension` I can use `layout: 'layouts/layout'`.

**Comment by mcollina** [comment]
Go for the code fix!

**Comment by jorgevrgs** [comment]
> Go for the code fix!

https://github.com/jorgevrgs/point-of-view/commit/5fdc5053e0e9ea27356db8ec3fdfbc13ea74aa04

I'm trying a solution, but please check below the benchmark results with `autocannon`:

Original:
Express 97.5% --> 8199
Fastify 97.5% --> 16607

Modification:
Express 97.5% --> 7487
Fastify 97.5% --> 14231

It's better to improve documentation instead of sacrificing performance, isn't it?

**Comment by mcollina** [comment]
Ouch :/. Yes

**Comment by zekth** [comment]
I feel that a map of accessible layout should be added as cache in the lib. As there is already one `lru` for the `getTemplate` function

**Comment by jorgevrgs** [comment]
With cache results:

Original: 97.5% 15391 Avg  12659.6
Cached: 97.5% 18735 Avg 15282.8

https://github.com/fastify/point-of-view/compare/master...jorgevrgs:master

**Comment by mcollina** [comment]
send that as a PR ;). I would use a different instance of the cache.

**Comment by jorgevrgs** [comment]
> send that as a PR ;). I would use a different instance of the cache.

I sent you a PR. Thanks.

https://github.com/fastify/point-of-view/pull/238

**Comment by danielkhan** [comment]
Seems this was fixed via
- #238
