### ISSUE TITLE
propertyName for interface

### ISSUE THREAD

**Issue by jorgevrgs** [fastify/point-of-view#252]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Replace the next code:

``` typescript
declare module "fastify" {
  interface FastifyReply {
    view(page: string, data?: object): FastifyReply;
  }
}
```
For something similar to this one:

``` typescript
declare module "fastify" {
  interface FastifyReply {
   [propertyName: string](page: string, data?: object): FastifyReply;
  }
}
```

To allow the use of custom property names.

### Motivation

Using Typescript when you define a property name is not possible to get the right types.

### Example

For instance: defined propertyName as `viewEmail` instead of the default `view`, so that you won't be able to get the right types.

**Comment by climba03003** [comment]
When you need a custom property, you should declare type yourself.

Your proposal is convenient for a single plug-in, but cause a lot of trouble when combining different plug-in type augmentation.

**Comment by jorgevrgs** [comment]
Yeah! that's a problem that `point-of-view` is not behind a kind of wrapper for this. Thanks for the answer. So, better to give some tips on the documentation.
