### ISSUE TITLE
 Property 'view' does not exist on type 'FastifyReply

### ISSUE THREAD

**Issue by khushal123** [fastify/point-of-view#271]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.0.0

### Plugin version

4.15.2

### Node.js version

16

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

reply. view property is not available if the project is created with typescript fastify-cli
Example code:

```
import { join } from 'path';
import AutoLoad, { AutoloadPluginOptions } from 'fastify-autoload';
import { FastifyPluginAsync } from 'fastify';



export type AppOptions = {
  // Place your custom options for app below here.
} & Partial<AutoloadPluginOptions>;

const app: FastifyPluginAsync<AppOptions> = async (
  fastify,
  opts
): Promise<void> => {
  // Place here your custom code!

  void fastify.register(require("fastify-websocket"))

  void fastify.register(require('point-of-view'), {
    engine: {
      ejs: require('ejs'),
    },
    root: join(__dirname, 'views/html'),
  })

  // Do not touch the following lines

  // This loads all plugins defined in plugins
  // those should be support plugins that are reused
  // through your application
  void fastify.register(AutoLoad, {
    dir: join(__dirname, 'plugins'),
    options: opts
  })

  // This loads all plugins defined in routes
  // define your routes in one of these
  void fastify.register(AutoLoad, {
    dir: join(__dirname, 'routes'),
    options: opts
  })

};

export default app;
export { app }
```

### Steps to Reproduce

in route.ts file:

```
const listen: FastifyPluginAsync = async (fastify, opts): Promise<void> => {

    fastify.get('/', async function (request, reply) {
        reply.view("listen.ejs")
    })
}
```

I have added the views folder parallel to the app.ts file. 

Please find a screenshot
![image](https://user-images.githubusercontent.com/12594221/142730786-d8841a78-0963-4914-a789-2e7b9309866a.png)

**Comment by climba03003** [comment]
Please use `import package from 'package'` when you are using TypeScript.
It is needed for the TypeScript type system and allow the type augmentation.

Another thing is that `autoload` is not user-friendly for type augmentation.

**Comment by khushal123** [comment]
Thanks, it works with import.
