### ISSUE TITLE
Restructure and review the docs

### ISSUE THREAD

**Issue by danielkhan** [fastify/point-of-view#279]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

While the `README` covers most features, it's a bit hard to read.

E.g.
> If you want to omit view extension, you can add `includeViewExtension` property as following
This assumes that a user knows what the module means with `view extension`. It could rather mean some mechanism of extending views or the file extension (which it is).

As I just added a new feature in #278, I would volunteer to give this a stab when documenting the feature.

### Motivation

Everyone likes comprehensive docs :)

**Comment by mcollina** [comment]
Go for it!
