### ISSUE TITLE
Need clarification on options for includes for EJS

### ISSUE THREAD

**Issue by danielkhan** [fastify/point-of-view#280]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

In the [README](https://github.com/danielkhan/point-of-view/blob/master/README.md?plain=1#L140), the documentation states that specific options need to be defined to support includes for EJS and also the [tests](https://github.com/fastify/point-of-view/blob/master/test/test-ejs.js#L756) follow this practice.

Yet, when looking into the [view renderer for EJS](https://github.com/fastify/point-of-view/blob/master/index.js#L294) the global options are never applied. Also, when running the tests with these options commented out, they pass.

Is my assumption correct, that these options are superfluous/never used?

**Comment by mcollina** [comment]
You likely have more fresh knowledge of the internals of this module ;). They are definitely redundant if the test pass.
