### ISSUE TITLE
default encoding in views

### ISSUE THREAD

**Issue by smartiniOnGitHub** [fastify/point-of-view#29]
Hi all,
I just see that if I don't set in explicit way reply encoding, Firefox will complaint on missing encoding.
So for reply.view I need to do (anytime) something like:
reply.type('text/html; charset=utf-8').view('index', data)

What do you think on adding that encoding as default for views (could be a good default) ?
Or check the encoding of related view (file) ... but this could be too much and alittle more expensive in performances.

What do you think ?

Thanks,
Sandro

**Comment by mcollina** [comment]
I’m +1 on setting the mime type every time in this plugin if it is not set when calling view. PR?

**Comment by smartiniOnGitHub** [comment]
ok, give me only some days to understand where (and how :-) ) to do changes ...

**Comment by smartiniOnGitHub** [comment]
Sorry, could you merge (if good enough) my other PR so here I can start from an updated master ?
Thanks a lot and sorry for this request :-) .

**Comment by mcollina** [comment]
We should be good now!

**Comment by smartiniOnGitHub** [comment]
@mcollina you beat me over time on this PR :-) .
Sorry but for the changes in this PR my intention was to put that encoding as default in the plugin (when serving pages), so I think changing this line:
`        that.header('Content-Type', 'text/html').send(html)
`
and then cleanup any reference to '; charset=utf-8' ... 
But my idea is right (for how this plugin works) ?
Or is it a behavior wanted here (I think it will be safer and should not do damage nor problems) ?

**Comment by mcollina** [comment]
No big deal, reopening! Feel free to send a new PR!

**Comment by smartiniOnGitHub** [comment]
https://github.com/fastify/point-of-view/pull/31
All should be done ... anyway tell me if there is some change or improvement still to do.
Thanks, Sandro

**Comment by smartiniOnGitHub** [comment]
Previous PR closed (was outdated), the new one is [#35](https://github.com/fastify/point-of-view/pull/35)

**Comment by smartiniOnGitHub** [comment]
PR has been merged.
