### ISSUE TITLE
unable to access template "./templates/layout"

### ISSUE THREAD

**Issue by evaasmakula** [fastify/point-of-view#303]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.28.0

### Plugin version

5.2.0

### Node.js version

 https://github.com/fastify/point-of-view/issues/new?assignees=&labels=&template=bug.yml

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11 (10.0.22000 22000)

### Description

When i'am trying to use template for Handlebars its says error `unable to access template "./templates/layout"`

### Steps to Reproduce

```
app.register(pov, {
    engine: {
        handlebars: require('handlebars')
    },
    layout: path.join(__dirname, 'views/main.hbs'),
    root: './views/',
});
```

**Comment by jonnow** [comment]
Believe I'm having the same issue, the layout file is being ignored. I've gone into the test file and the 'examples-eps-with-some-options.js' and changed it to use handlebars and it works fine. 

When I try to use a layout in my project it seems to be completely overlooking the layout file.

Folder structure:
- templates/
- - layouts/
- - - main.hbs
- - index.hbs
- index.js

index.js:
```
const fastify = require('fastify')(),
    templatesFolder = 'templates',

fastify.register(require("point-of-view"), {
    engine: {
        handlebars: require("handlebars"),
    },
    layout: "./templates/layout/main.hbs",
    includeViewExtension: true, 
    templates: templatesFolder,
    options: {
        partials: {
            nav: 'nav'
        }
    }
});

fastify.get("/", (req, reply) => {
    reply.view("index", { text: "text" });
  });
```

main.hbs (layout file)
```<!DOCTYPE html>
<html lang="en">
  <head></head>
  <body>
    <h1>Heading</h1>
    {{{body}}}
  </body>
</html>
```

index.hbs:
```
<p>{{text}}</p>
```

**Comment by jonnow** [comment]
Ensure your versions of fastify and point-of-view are up-to-date and it should work 🤦🏻 I just created a new project using the following versions in my package.json file and it is now working. 

Using the "example-ejs-with-some-options.js" files and others from the master branch doesn't seem to work with layout and partials.

Package.json
```
{
    "name": "handlebars-test",
    "version": "0.0.1",
    "description": "Running up-to-date packages to get handlebars working with layouts and partials",
    "scripts": {
        "devStart": "nodemon index.js"
    },
    "dependencies": {
        "fastify": "^3.28.0",
        "handlebars": "^4.7.7",
        "nodemon": "^2.0.15",
        "point-of-view": "^5.2.0"
    }
}
```


Index.js
```
const fastify = require('fastify')()
const data = { text: 'Hello world from the data' }

fastify.register(require('point-of-view'), {
    engine: {
        handlebars: require('handlebars')
    },
    layout: './views/main.hbs',
    options: {
        partials: {
            nav: './views/nav.hbs'
        }
    }
})

fastify.get('/', (req, reply) => {
    reply.view('./views/index.hbs', data)
})

fastify.listen(3000, err => {
    if(err) throw err
    console.log(`server listening on ${fastify.server.address().port}`)
})
```


main.hbs:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome!</h1>
    {{body}}
</body>
</html>
```

index.hbs:
```
{{ text }}
{{> nav}}
```

nav.hbs:
```
This is the nav file
```
Output in browser:
![Screenshot 2022-04-13 at 11 06 34](https://user-images.githubusercontent.com/1215325/163155290-6b3f7ee0-4276-40bd-b247-30b65743e16e.png)

**Comment by bacloud22** [comment]
Same as me, neither the absolute nor the relative path works. 
I'm using the latest versions: 
Fastify: 4.2.0
@fastify/view: 7.0.0

**Comment by Eomm** [comment]
Could you add a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

Without it, we are unable to help you.

**Comment by bacloud22** [comment]
thank you @Eomm 
It was resolved, sorry for not following,

What I can say is that on Linux
`reply.view('filename')` works
Where in Windows, only
`reply.view('./filename')` work.
