### ISSUE TITLE
FST_ERR_PLUGIN_VERSION_MISMATCH

### ISSUE THREAD

**Issue by Galaxy-Coding** [fastify/point-of-view#310]
Getting this error: 

![](https://i.ibb.co/Vq6TvXV/Screenshot-2022-05-11-9-52-23-PM.png)
My dependencies:
![](https://i.ibb.co/q5154s2/Screenshot-2022-05-11-9-52-12-PM.png)

**Comment by climba03003** [comment]
You should use `point-of-view@5`.

**Comment by mcollina** [comment]
My fault. I accidentally tagged point-of-view@6.0.0 as latest instead of next.

**Comment by climba03003** [comment]
It seems like `point-of-view` is not the only case.
`fastify-helmet` also suffer.
https://github.com/fastify/fastify/issues/3900
