### ISSUE TITLE
async: true as an option of .view() for ejs causes an error

### ISSUE THREAD

**Issue by TTPO100AJIEX** [fastify/point-of-view#312]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.29.0

### Plugin version

5.3.0

### Node.js version

18.0.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description

The abstraction does not allow for asynchronous rendering of templates.
If you pass **"async": true** as an option for the renderer, ejs's **compile()** (or, probably, other function like **renderFile()**) returns a promise which is, apparently, directly passed to **<reply>.send()** by **point-of-view** which causes an error **Attempted to send payload of invalid type 'object'. Expected a string or Buffer.** The promise should be resolved before being passed to **.send()**.
Probable solution: await the **compile()** function if **async: true** is present in the options object.

### Steps to Reproduce

1) install fastify, point-of-view, ejs.
2) Create two files in the directory with the project:
index.js:
```
import fastify from 'fastify';
import point_of_view from "point-of-view";
import ejs from 'ejs';
const app = fastify({ logger: true });
await app.register(point_of_view, { "engine": { "ejs": ejs }, "options": { "async": true } });
app.get('/*', async (req, res) => res.view("index.ejs") );
app.listen(80, "0.0.0.0");
```
index.ejs:
```
<html>
    <head></head>
    <body>
        <% async function test() { return(2); } %>
        <%- await test(); %>
    </body>
</html>
```
3) Run the application by typing **node index.js** in the console.
4) Open **http://127.0.0.1:80** in any browser.
5) Get the error
```
...node_modules\fastify\lib\reply.js:506
    throw new FST_ERR_REP_INVALID_PAYLOAD_TYPE(typeof payload)
    ^
FastifyError [Error]: Attempted to send payload of invalid type 'object'. Expected a string or Buffer.
    at onSendEnd (F:\bots\.tmps\fastify\node_modules\fastify\lib\reply.js:506:11)
    at onSendHook (F:\bots\.tmps\fastify\node_modules\fastify\lib\reply.js:447:5)
    at Reply.send (F:\bots\.tmps\fastify\node_modules\fastify\lib\reply.js:199:3)
    at _readCallback (F:\bots\.tmps\fastify\node_modules\point-of-view\index.js:280:12)
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  code: 'FST_ERR_REP_INVALID_PAYLOAD_TYPE',
  statusCode: 500
}
```

### Expected Behavior

The template gets correctly rendered and a page with just "2" gets sent to the user.

**Comment by mcollina** [comment]
Is async rendering of templates supported by ejs?

We might want to detect if there is a promise and in case await that.

Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by TTPO100AJIEX** [comment]
Yes, ejs does support async rendering. Until now, I have used raw ejs for that, and it worked as follow:
```
fastify.decorateReply("view", function (dir = "index.ejs", obj = {})
{
    let res = this;
    ejs.renderFile(`views/${dir}`, obj, {async: true}, async function(err, str)
    {
        if (err)
        {
            try{ res.status(500).send(await err); } catch(err) { res.status(500).send(err); }
            return;
        }
        try
        {
            res.header("Content-Type", "text/html; charset=UTF-8");
            res.status(200).send(await str);
        } catch(err) { res.status(500).send(err); }
    });
});
```
Notice how **renderFile** itself is async (similar to **compile**), and **.send** also gets **await str**.

I will try to fork the repository now, and attempt to fix it myself. I will make a pull request if I succeed.

**Comment by mcollina** [comment]
Thanks!
