### ISSUE TITLE
Referencing a variable that does not exist can cause an entire fastify exception  

### ISSUE THREAD

**Issue by zhenruyan** [fastify/point-of-view#32]
When referring to the wrong variable, express gets an exception rather than hangs, but when fastify, it causes the entire program to die.

**Comment by mcollina** [comment]
I think fastify is doing the correct thing. If your application throw it is better to crash, otherwise you are going to leak memory.

What we can do is to catch and send that to the error handler... the user will see a 500. Would this be bettere?

**Comment by zhenruyan** [comment]
So how do I catch this exception, it seems to be in the form of Plug-ins, in the plug-in callback? or where?

**Comment by mcollina** [comment]
very likely we would have to add it in this library.

Would you mind sending a PRA?

**Comment by smartiniOnGitHub** [comment]
Hi all, I just started an implementation for this (I have the same problem even when an EJS include file is missing and I need to have it fxed), I hope to push something for a PR in a few days ...

**Comment by smartiniOnGitHub** [comment]
To speedup development cycles in some projects I use [nodemon](https://www.npmjs.com/package/nodemon) ... if I'd add it in dev dependencies here and add a custom npm command to have an hot-reloadable dev server ?
@mcollina What do you think ?

**Comment by mcollina** [comment]
The best way to develop this is via unit tests, not with a “hot-reloadable dev server”, I’m kind of -1. There is no need to add this to package.json either as you can use it from a global installation.

**Comment by smartiniOnGitHub** [comment]
@mcollina ok. I just created the [PR33](https://github.com/fastify/point-of-view/pull/33).
Due to lack of time now it's without tests but I'll add them in a few days.
As always comments and suggestions are welcome :-) ... thanks for now. Bye

**Comment by zhenruyan** [comment]
@smartiniOnGitHub  Thank you very much.

**Comment by smartiniOnGitHub** [comment]
@mcollina This could be closed now (just merged) ... thanks a lot.
