### ISSUE TITLE
Dependency version mismatch

### ISSUE THREAD

**Issue by andriichern** [fastify/point-of-view#320]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.29.0

### Plugin version

6.2.1

### Node.js version

16.7.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.3.1

### Description

I believe it just a simple typo bug.

Plugin itself requires `fastify` version at least 4.x while latest released version is 3.29.0.
At the same time docs also says it expects at least version 2.x.

Code from `index.js` file:
```
module.exports = fp(fastifyView, {
  fastify: '4.x',
  name: 'point-of-view'
})
```

### Steps to Reproduce

Just install it in a 'fresh' project :)

**Comment by Fdawgs** [comment]
Use v5.3.0 if you need Fastify v3.x support.

Fastify v4 is being released soon, and the plugins have been updated ahead of it.
See the work done in https://github.com/fastify/fastify/issues/3482

**Comment by andriichern** [comment]
Ok, thx!
