### ISSUE TITLE
Deoptimized access to `reply.locals`

### ISSUE THREAD

**Issue by mmarti** [fastify/point-of-view#349]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Plugin version

latest

### Description

Not sure if this is a bug or just a docs issue.  The docs state:

>If you want to provide data, which will be depended on by a request and available in all views, you have to add property `locals` to `reply` object ...

But it doesn't look like a decorator is ever added from `@fastify/view`'s side.  Is it expected the app manually decorates the reply with locals before registering the plugin, or should the plugin automatically register it?

Theoretically the following code should be somewhere; I just don't know the recommended where 😆:

```mjs
fastify.decorateReply('locals', null);

fastify.addHook('onRequest', async (request, reply) => {
  reply.locals = {};
});
```

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

Adding this in the main plugin function would be ok.

**Comment by Uzlopak** [comment]
Yes, you basically write a test where you register the plugin and then inject a request and test only if the field is added to the request-object.
