### ISSUE TITLE
Allow custom `Content-Type` header for Nunjucks

### ISSUE THREAD

**Issue by smigles** [fastify/point-of-view#353]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.2.0

### Plugin version

7.1.2

### Node.js version

16.13.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 20.04

### Description

Currently, you cannot set a custom `Content-Type` header if you use Nunjucks template engine. `text/html; charset=utf-8` is always sent.

It is similar to #9

### Steps to Reproduce

1. Set Nunjucks as the template engine.
2. For example write:
```js
reply.type('application/xml');
return reply.view('template.njk', { data });
```
3. `Content-Type` response header is `text/html; charset=utf-8`.

### Expected Behavior

`Content-Type` response header is `application/xml; charset=utf-8`.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
