### ISSUE TITLE
Update nunjucks to latest release

### ISSUE THREAD

**Issue by smartiniOnGitHub** [fastify/point-of-view#38]
Hi all,
I just see that a new release of Nunjucks is available, so could be good to use it.
See [here](https://github.com/mozilla/nunjucks/releases).
And update other dependencies too, but keep Fastify to pre-1.0.x (0.43.0), ok ?

**Comment by mcollina** [comment]
(in package.json, not in the file).

**Comment by smartiniOnGitHub** [comment]
@mcollina the PR is [PR#39](https://github.com/fastify/point-of-view/pull/39) ... thanks for now. Ciao

**Comment by mcollina** [comment]
Released as 0.8.0.

**Comment by smartiniOnGitHub** [comment]
@mcollina Top !!
