### ISSUE TITLE
Is the latest version (9.1.0) not published to npm?

### ISSUE THREAD

**Issue by yb** [fastify/point-of-view#425]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I noticed that 9.1.0 has been released for a few days, but the latest version on npm is 9.0.0 ([via](https://www.npmjs.com/package/@fastify/view?activeTab=versions))
How to install 9.1.0 from npm?

Async rendering in 9.0.0 seems to have some issues with `html-minifier-terser` :(

Thanks

**Comment by mcollina** [comment]
Good spot, fixed
