### ISSUE TITLE
Bug:  The root path is spliced repeatedly.

### ISSUE THREAD

**Issue by byteslaves** [fastify/point-of-view#437]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.28.1

### Plugin version

9.1.0

### Node.js version

20

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

win11

### Description

Upon employing this plugin, utilizing art-template as the template engine, and assigning a path to the root property, an error ensues due to the unintended concatenation of two paths during the rendering process.
This behavior is not observed when using the EJS template engine. 

The relevant code snippet is provided below:

  fastify.register(fastifyView, {
    engine: {
      'art-template': require('art-template')
    },
    root:'./views/rat/'
  })
  
  fastify.get("/art", (req, reply) => {
    reply.view('./index.art', { text: "text" });
  });

error message:
    err: {
      "type": "Error",
      "message": "template not found: ENOENT: no such file or directory, open 'S:\\user\\js-ts-project\\fastify\\hello-world\\views\\rat\\views\\rat\\index.art'",
      "stack":
          TemplateError: template not found: ENOENT: no such file or directory, open 'S:\user\js-ts-project\fastify\hello-world\views\rat\views\rat\index.art'
      "name": "TemplateError"
    }

Big thanks to all the Fastify contributors!

### Expected Behavior

Can access the directory correctly

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
