### ISSUE TITLE
Multiple Templates Directory (with Template Inheritance)

### ISSUE THREAD

**Issue by exequiel09** [fastify/point-of-view#49]
Is multiple templates directory like the one below supported? Since some of the template engines supported allows extension of templates (template inheritance) from other templates (e.g. `nunjucks`).

```
root
└───modules
│   │   └───home
│   │   │   │   index.js
│   │   │   └───templates
│   │   │   │   └───home
│   │   │   │   │   │   home-template1.html (inherits from base.html)
│   │   │   │   │   │   home-template2.html (inherits from base.html)
│   │   └───about
│   │   │   │   index.js
│   │   │   └───templates
│   │   │   │   └───about
│   │   │   │   │   │   home-template1.html (inherits from base.html)
│   │   │   │   │   │   home-template2.html (inherits from base.html)
└───templates
│   │   base.html
```

**Comment by mcollina** [comment]
I don't think so. However, you can instantiate point-of-view in separate plugins. So you can have different part of the application using different point-of-view configuration.

Anyway, would you like to send a PR?

**Comment by exequiel09** [comment]
The thing is you wont get to access the top-most templates dir which you can use to place the base template and extend it from the other modules.

> I don't think so. However, you can instantiate point-of-view in separate plugins. So you can have different part of the application using different point-of-view configuration.

This would require a lot of refactoring since `templatesDir` requires only string and other templating engines have a different mechanism on how extending template works. The above structure is somewhat similar to [Flask Blueprints](http://flask.pocoo.org/docs/0.12/blueprints/#templates) in Python.

**Comment by exequiel09** [comment]
# Templating Engines (Template Inheritance and Template Inclusion) Summary

This table shows the templating engines currently supported alongside with their support for template inheritance and template inclusion. (This list is just based on my research and may contain errors)

| Template Engine        | Template Inheritance          | Template Inclusion        |
| ---------------------- |-------------------------------| ------------------------- |
| `ejs`                  | No                            | [Yes][ejs-partial]        |
| `ejs-mate`             | [Yes][ejs-mate-inheritance]   | [Yes][ejs-mate-partial]   |
| `nunjucks`             | [Yes][nunjucks-inheritance]   | [Yes][nunjucks-include]   |
| `pug`                  | [Yes][pug-inheritance]        | [Yes][pug-include]        |
| `handlebars`           | No                            | [Yes][handlebars-include] |
| `marko`                | No                            | [Yes][marko-include]      |

[nunjucks-inheritance]: https://mozilla.github.io/nunjucks/templating.html#template-inheritance
[nunjucks-include]: https://mozilla.github.io/nunjucks/templating.html#include
[pug-inheritance]: https://pugjs.org/language/inheritance.html
[pug-include]: https://pugjs.org/language/includes.html
[handlebars-include]: http://handlebarsjs.com/partials.html
[marko-include]: https://markojs.com/try-online/?file=%2Fmarko-language-guide%2Fcomponents%2Flayouts%2Findex.marko&gist=
[ejs-mate-inheritance]: https://github.com/JacksonTian/ejs-mate#blockname
[ejs-mate-partial]: https://github.com/JacksonTian/ejs-mate#partialnameoptionsorcollection
[ejs-partial]: http://www.embeddedjs.com/examples/partials.html

**Comment by mcollina** [comment]
This would be a very useful feature. Would you like to file a PR with this?

**Comment by exequiel09** [comment]
Sorry @mcollina i was busy this past few days. I can't as of the moment so many tasks to do. Will just leave it here open so anyone can look it into it. If i have time i'll just bring it up here that i have filed a PR.

**Comment by dtex** [comment]
Working on a PR for Mustache which supports template inclusion ("partials" in mustache-land) and am considering how best to handle this. I have a proposal and a question:

1. Most of the view signatures in POV are ```viewEngineName(pagePath, data)``` except for Marko and now Mustache which both are ```viewEngineName(pagePath, data, options)```. The only available property on Marko options (currently) is ```stream``` and the only one on Mustache is ```partials```. I propose that these two properties be the starting point for defining a common, optional ```options``` parameter that is the same for all engines. Not all engines will support all the properties of course but it will give us a common API.
1. When view is called the templates are loaded from disk via fs. With partials (included templates) we could be loading several or even dozens of template files on every view. Would it be better to leverage the existing LRU cache when loading template files instead of always depending on fs?

**Comment by mcollina** [comment]
I'm +1 for both proposals.

**Comment by cemremengu** [comment]
Did mustache support solved this issue?
