### ISSUE TITLE
Change dependency on request with simple-get

### ISSUE THREAD

**Issue by smartiniOnGitHub** [fastify/point-of-view#57]
Hi all,
for consistency with Fastify (and with some other core plugins) I think could be useful to change the devDependency from 'request' to latest 'simple-get', and maybe update all other dependencies ...
What do you think ?
If accepted, I'll do a PR with changes (even related tests of course).

Thanks, Sandro

**Comment by mcollina** [comment]
+1 to a PR!

**Comment by smartiniOnGitHub** [comment]
PR done. Note that I updated all dependencies to latest release, and updated even plugin release ... hope all is good. Bye

**Comment by mcollina** [comment]
Thanks!
