### ISSUE TITLE
Nunjucks support

### ISSUE THREAD

**Issue by enix-app** [fastify/point-of-view#80]
```js
{
  engine: {
    njk: require('nunjucks')
  }
}
````

Not working.

**Comment by esakkikrishnan** [comment]
Was able to get the rendering but unable to use Nunjucks Global variable

**Comment by enix-app** [comment]
I did change:

```js
{
  engine: {
    nunjucks: require('nunjucks')
  }
}
````

Working now.

**Comment by esakkikrishnan** [comment]
@enix-app but were you able to use nunjucks global variables

**Comment by enix-app** [comment]
I have not tried it yet.

**Comment by Extarys** [comment]
I'm using nunjucks and it's working flawlessly.
`yarn add point-of-view nunjucks`

index.js:
```
fastify.register(require('point-of-view'), {
  engine: {
    nunjucks: require('nunjucks')
  },
  templates: './build/views',
  includeViewExtension: true
})
```

**Comment by ezk2410** [comment]
@Extarys tried using global variables ?

**Comment by Extarys** [comment]
@ezk2410 Oops I may have replied to fast, I didn't test with global variables. Can you post here how you added them?

**Comment by farzer** [comment]
another way to support this feature at #119

**Comment by Eomm** [comment]
Closing since ninjucks is now supported thks to contributors 💪
