### ISSUE TITLE
Add type definition for typescript usage.

### ISSUE THREAD

**Issue by alxolr** [fastify/point-of-view#84]
Missing type-definition for typescript usage. Will try to help with that.

**Comment by mcollina** [comment]
would you like to send a pull request?

Il giorno mar 13 nov 2018 alle 18:28 Alexandru Olaru <
notifications@github.com> ha scritto:

**Comment by alxolr** [comment]
Hi Mateo, yep working on it, hope tomorrow to be able to finish it.
