### ISSUE TITLE
Refactoring to support async/await

### ISSUE THREAD

**Issue by mcollina** [fastify/point-of-view#87]
I think it's due that we improve the support for async/await in this module.

Currently, it's not working as expected mainly because loading templates could be asynchronous, and that does not work well with the internal call to `.send()`, as there is no way to await that.

It following should work with any template engine.

What we need as next steps is a proposal to implement an API that could be awaited upon, and then an implementation.

**Comment by jamilservicos** [comment]
i use:

```
return await app.view("template/index", {teste: "hello"}).then(html => {
                    return reply.code(200)
                        .header('Content-Type', 'text/html; charset=utf-8')
                        .send(html);
                });
```

**Comment by mcollina** [comment]
That's a good one @jamilservicos!

It's the `reply.view`  one that's not working well IMHO.

Note that I would prefer the following:

```js
const html = await app.view("template/index", {teste: "hello"})
reply.code(200).header('Content-Type', 'text/html; charset=utf-8')
return html
```

**Comment by Hamper** [comment]
I'm just rewite previous decorator in async style:
```javascript
fastify.decorate('render', async (view, options, reply) => {
    return reply.code(200)
        .header('Content-Type', 'text/html; charset=utf-8')
        .send(await fastify.view(view, options));
});
```
