### ISSUE TITLE
Error with ejs-mate: cb is not a function

### ISSUE THREAD

**Issue by goliatone** [fastify/point-of-view#90]
Getting the following error when rendering a view using the `ejs-mate@3.0.0` engine:

```json
{
  "level": 50,
  "time": 1545039516427,
  "msg": "cb is not a function",
  "pid": 5396,
  "hostname": "goliatorum.home",
  "reqId": 1,
  "req": {
    "id": 1,
    "method": "GET",
    "url": "/login",
    "hostname": "127.0.0.1:3003",
    "remoteAddress": "127.0.0.1",
    "remotePort": 53826
  },
  "res": { "statusCode": 500 },
  "err": {
    "type": "TypeError",
    "message": "cb is not a function",
    "stack": "TypeError: cb is not a function\n    at Function.compile (/src/node_modules/ejs-mate/lib/index.js:130:3)\n    at _readCallback (/src/node_modules/point-of-view/index.js:139:39)\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:528:3)"
  },
  "v": 1
}
```

This is due to `ejs-mate` expecting a callback in their compile function:
```js
function compile(file, options, cb) 
```

* point-of-view: 2.1.0

**Comment by cemremengu** [comment]
I will take a look at this, unfortunately it supports only version `2.3.0` atm

**Comment by cemremengu** [comment]
@goliatone if you would like to submit a PR I will take at as well :)

**Comment by goliatone** [comment]
@cemremengu Sorry, missed the comment. I ended up having to fork both point-of-view and ejs-mate. The way it was setup locals were not being properly propagated, I ended up adding a couple more  features, meaning it might not be a straight PR to either project.

**Comment by TheRTK** [comment]
Hello! 
I think you try use `ejs` engine for `ejs-mate` 

I had same problem with this code:

```
fastify.register(require('point-of-view'), {
    engine: {
      ejs: require('ejs-mate')
    },
    includeViewExtension: true,
    templates: './templates',
    options: {
      filename: resolve('templates')
    }
  });
```

Then i change engine `ejs` to `ejs-mate` and now its working:

```
  fastify.register(require('point-of-view'), {
    engine: {
      'ejs-mate': require('ejs-mate') // here need set 'ejs-mate'
    },
    includeViewExtension: true,
    templates: './templates',
    options: {
      filename: resolve('templates')
    }
  });
```

**Comment by goliatone** [comment]
@TheRTK it would not surprise me that I made a silly mistake like that. However, I wanted to add support for some features I had in my previous setup like being able to resolve views from different view folders, a better way to manage locals (config file with locals per route, defaults, merging, etc). Thanks for the heads up tho!

**Comment by calumk** [comment]
Hello all, any progress on this? 

Could I suggest a reference to requiring 2.3.0 is added to the readme? 
I spent about half an hour trying to figure out why it wasn't working, including reading this thread twice, before realising that the sample @TheRTK  provided as "working" was only "working" on their modified branch

**Comment by Eomm** [comment]
Improving the readme is always a good idea! Would you like to add this?

There is a PR https://github.com/fastify/point-of-view/pull/81 to discuss to update to ejs-mate 3.0.0 but seems stalled due to the project inactivity.
