### ISSUE TITLE
Add extension for handlebars

### ISSUE THREAD

**Issue by leomleao** [fastify/point-of-view#93]
Handlebars engine very commonly uses the extension ".hbs", although point-of-view is not configure for it.

**Comment by Eomm** [comment]
This should be supported:
https://github.com/fastify/point-of-view/blob/e91f31f3c16b657afdcf41c5365010dfcf4eddfc/index.js#L32

Do you notice some bugs?

**Comment by amer8** [comment]
I agree `*.hbs` is being used in Ember.js or Assemble and that case should be supported with a higher priority, while `*.handlebars` should be valid too.
Currently `*.hbs` extension is the default extension and it's supported https://github.com/fastify/point-of-view/blob/master/index.js#L310 and there's no support for `*.handlebars` in combination with `includeViewExtension: true` option.

**Comment by Eomm** [comment]
Would you like to send a PR to support it? 🤟

**Comment by amer8** [comment]
I don't want to support `*.handlebars` extension (not necessary complexity). As point-of-view supports `*.hbs` i think this issue can be closed.
